matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode11.5
xcode_scheme: AlgoBrainTests
script:
  - swift test -c release -Xswiftc -enable-testing
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
