matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode11.5
xcode_scheme: AlgoBrainTests
script:
  - swift test -c release -Xswiftc -enable-testing
  - xcodebuild -scheme AlgoBrain -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build test --cover-xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
